- name: Part 1
  hosts: localhost
  vars:
    rucksack: "{{ lookup('file', 'input.txt') | split('\n') }}"
    sum: 0
    priorities:
      - "a"
      - "b"
      - "c"
      - "d"
      - "e"
      - "f"
      - "g"
      - "h"
      - "i"
      - "j"
      - "k"
      - "l"
      - "m"
      - "n"
      - "o"
      - "p"
      - "q"
      - "r"
      - "s"
      - "t"
      - "u"
      - "v"
      - "w"
      - "x"
      - "y"
      - "z"
      - "A"
      - "B"
      - "C"
      - "D"
      - "E"
      - "F"
      - "G"
      - "H"
      - "I"
      - "J"
      - "K"
      - "L"
      - "M"
      - "N"
      - "O"
      - "P"
      - "Q"
      - "R"
      - "S"
      - "T"
      - "U"
      - "V"
      - "W"
      - "X"
      - "Y"
      - "Z"
  tasks:
    - name: Calculate the priorities
      ansible.builtin.include_tasks:
        file: part1priorities.yaml
      loop: "{{ rucksack }}"

    - name: Print the sum
      ansible.builtin.debug:
        msg: "{{ sum }}"
