- name: Part 2
  hosts: localhost
  vars:
    games: "{{ lookup('file', 'input.txt') | split('\n') }}"
    score: 0
  tasks:
    - name: Play through the Rock-Paper-Scissors games
      ansible.builtin.include_tasks:
        file: part2game.yaml
      loop: "{{ games }}"

    - name: Print the total score
      ansible.builtin.debug:
        msg: "{{ score }}"
