- name: Part 2
  hosts: localhost
  vars:
    elves: "{{ lookup('file', 'input.txt') | split('\n\n') }}"
  tasks:
    - name: Calculate the sum of the calories that each Elf is carrying
      ansible.builtin.debug:
        msg: "{{ item | split('\n') | map('int') | sum }}"
      loop: "{{ elves }}"
      register: calories

    - name: Sort the list of calorie sum
      ansible.builtin.set_fact:
        calories_sorted: "{{ calories['results'] | map(attribute='msg') | map('int') | sort }}"

    - name: Print the calorie sum of the top 3 Elves carrying the most calories
      ansible.builtin.debug:
        msg: "{{ calories_sorted[-3:] | sum }}"
